// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageType.proto

package com.kanven.schedual.network.protoc;

public final class MessageTypeProto {
  private MessageTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * Protobuf enum {@code com.kanven.schedual.network.protoc.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>TASK = 0;</code>
     */
    TASK(0),
    /**
     * <pre>
     *心跳检查
     * </pre>
     *
     * <code>PING = 1;</code>
     */
    PING(1),
    /**
     * <pre>
     *心跳检查
     * </pre>
     *
     * <code>PONG = 2;</code>
     */
    PONG(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>TASK = 0;</code>
     */
    public static final int TASK_VALUE = 0;
    /**
     * <pre>
     *心跳检查
     * </pre>
     *
     * <code>PING = 1;</code>
     */
    public static final int PING_VALUE = 1;
    /**
     * <pre>
     *心跳检查
     * </pre>
     *
     * <code>PONG = 2;</code>
     */
    public static final int PONG_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return TASK;
        case 1: return PING;
        case 2: return PONG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kanven.schedual.network.protoc.MessageTypeProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.kanven.schedual.network.protoc.MessageType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MessageType.proto\022\"com.kanven.schedual" +
      ".network.protoc*+\n\013MessageType\022\010\n\004TASK\020\000" +
      "\022\010\n\004PING\020\001\022\010\n\004PONG\020\002B\022B\020MessageTypeProto" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
