// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package com.kanven.schedual.network.protoc;

public final class RequestProto {
  private RequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kanven.schedual.network.protoc.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string requestId = 1;</code>
     */
    java.lang.String getRequestId();
    /**
     * <code>optional string requestId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
     */
    com.kanven.schedual.network.protoc.MessageTypeProto.MessageType getType();

    /**
     * <code>optional .com.kanven.schedual.network.protoc.Ping ping = 3;</code>
     */
    boolean hasPing();
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Ping ping = 3;</code>
     */
    com.kanven.schedual.network.protoc.RequestProto.Ping getPing();
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Ping ping = 3;</code>
     */
    com.kanven.schedual.network.protoc.RequestProto.PingOrBuilder getPingOrBuilder();

    /**
     * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
     */
    boolean hasTask();
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
     */
    com.kanven.schedual.network.protoc.RequestProto.Task getTask();
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
     */
    com.kanven.schedual.network.protoc.RequestProto.TaskOrBuilder getTaskOrBuilder();
  }
  /**
   * <pre>
   *请求实体
   * </pre>
   *
   * Protobuf type {@code com.kanven.schedual.network.protoc.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kanven.schedual.network.protoc.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      requestId_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              com.kanven.schedual.network.protoc.RequestProto.Ping.Builder subBuilder = null;
              if (ping_ != null) {
                subBuilder = ping_.toBuilder();
              }
              ping_ = input.readMessage(com.kanven.schedual.network.protoc.RequestProto.Ping.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ping_);
                ping_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.kanven.schedual.network.protoc.RequestProto.Task.Builder subBuilder = null;
              if (task_ != null) {
                subBuilder = task_.toBuilder();
              }
              task_ = input.readMessage(com.kanven.schedual.network.protoc.RequestProto.Task.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(task_);
                task_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kanven.schedual.network.protoc.RequestProto.Request.class, com.kanven.schedual.network.protoc.RequestProto.Request.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestId_;
    /**
     * <code>optional string requestId = 1;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string requestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
     */
    public com.kanven.schedual.network.protoc.MessageTypeProto.MessageType getType() {
      com.kanven.schedual.network.protoc.MessageTypeProto.MessageType result = com.kanven.schedual.network.protoc.MessageTypeProto.MessageType.valueOf(type_);
      return result == null ? com.kanven.schedual.network.protoc.MessageTypeProto.MessageType.UNRECOGNIZED : result;
    }

    public static final int PING_FIELD_NUMBER = 3;
    private com.kanven.schedual.network.protoc.RequestProto.Ping ping_;
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Ping ping = 3;</code>
     */
    public boolean hasPing() {
      return ping_ != null;
    }
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Ping ping = 3;</code>
     */
    public com.kanven.schedual.network.protoc.RequestProto.Ping getPing() {
      return ping_ == null ? com.kanven.schedual.network.protoc.RequestProto.Ping.getDefaultInstance() : ping_;
    }
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Ping ping = 3;</code>
     */
    public com.kanven.schedual.network.protoc.RequestProto.PingOrBuilder getPingOrBuilder() {
      return getPing();
    }

    public static final int TASK_FIELD_NUMBER = 4;
    private com.kanven.schedual.network.protoc.RequestProto.Task task_;
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
     */
    public boolean hasTask() {
      return task_ != null;
    }
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
     */
    public com.kanven.schedual.network.protoc.RequestProto.Task getTask() {
      return task_ == null ? com.kanven.schedual.network.protoc.RequestProto.Task.getDefaultInstance() : task_;
    }
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
     */
    public com.kanven.schedual.network.protoc.RequestProto.TaskOrBuilder getTaskOrBuilder() {
      return getTask();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
      }
      if (type_ != com.kanven.schedual.network.protoc.MessageTypeProto.MessageType.TASK.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (ping_ != null) {
        output.writeMessage(3, getPing());
      }
      if (task_ != null) {
        output.writeMessage(4, getTask());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
      }
      if (type_ != com.kanven.schedual.network.protoc.MessageTypeProto.MessageType.TASK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (ping_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getPing());
      }
      if (task_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getTask());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kanven.schedual.network.protoc.RequestProto.Request)) {
        return super.equals(obj);
      }
      com.kanven.schedual.network.protoc.RequestProto.Request other = (com.kanven.schedual.network.protoc.RequestProto.Request) obj;

      boolean result = true;
      result = result && getRequestId()
          .equals(other.getRequestId());
      result = result && type_ == other.type_;
      result = result && (hasPing() == other.hasPing());
      if (hasPing()) {
        result = result && getPing()
            .equals(other.getPing());
      }
      result = result && (hasTask() == other.hasTask());
      if (hasTask()) {
        result = result && getTask()
            .equals(other.getTask());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasPing()) {
        hash = (37 * hash) + PING_FIELD_NUMBER;
        hash = (53 * hash) + getPing().hashCode();
      }
      if (hasTask()) {
        hash = (37 * hash) + TASK_FIELD_NUMBER;
        hash = (53 * hash) + getTask().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kanven.schedual.network.protoc.RequestProto.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kanven.schedual.network.protoc.RequestProto.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求实体
     * </pre>
     *
     * Protobuf type {@code com.kanven.schedual.network.protoc.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kanven.schedual.network.protoc.Request)
        com.kanven.schedual.network.protoc.RequestProto.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kanven.schedual.network.protoc.RequestProto.Request.class, com.kanven.schedual.network.protoc.RequestProto.Request.Builder.class);
      }

      // Construct using com.kanven.schedual.network.protoc.RequestProto.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestId_ = "";

        type_ = 0;

        if (pingBuilder_ == null) {
          ping_ = null;
        } else {
          ping_ = null;
          pingBuilder_ = null;
        }
        if (taskBuilder_ == null) {
          task_ = null;
        } else {
          task_ = null;
          taskBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Request_descriptor;
      }

      public com.kanven.schedual.network.protoc.RequestProto.Request getDefaultInstanceForType() {
        return com.kanven.schedual.network.protoc.RequestProto.Request.getDefaultInstance();
      }

      public com.kanven.schedual.network.protoc.RequestProto.Request build() {
        com.kanven.schedual.network.protoc.RequestProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kanven.schedual.network.protoc.RequestProto.Request buildPartial() {
        com.kanven.schedual.network.protoc.RequestProto.Request result = new com.kanven.schedual.network.protoc.RequestProto.Request(this);
        result.requestId_ = requestId_;
        result.type_ = type_;
        if (pingBuilder_ == null) {
          result.ping_ = ping_;
        } else {
          result.ping_ = pingBuilder_.build();
        }
        if (taskBuilder_ == null) {
          result.task_ = task_;
        } else {
          result.task_ = taskBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kanven.schedual.network.protoc.RequestProto.Request) {
          return mergeFrom((com.kanven.schedual.network.protoc.RequestProto.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kanven.schedual.network.protoc.RequestProto.Request other) {
        if (other == com.kanven.schedual.network.protoc.RequestProto.Request.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasPing()) {
          mergePing(other.getPing());
        }
        if (other.hasTask()) {
          mergeTask(other.getTask());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kanven.schedual.network.protoc.RequestProto.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kanven.schedual.network.protoc.RequestProto.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requestId_ = "";
      /**
       * <code>optional string requestId = 1;</code>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestId = 1;</code>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestId = 1;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestId_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
       */
      public com.kanven.schedual.network.protoc.MessageTypeProto.MessageType getType() {
        com.kanven.schedual.network.protoc.MessageTypeProto.MessageType result = com.kanven.schedual.network.protoc.MessageTypeProto.MessageType.valueOf(type_);
        return result == null ? com.kanven.schedual.network.protoc.MessageTypeProto.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
       */
      public Builder setType(com.kanven.schedual.network.protoc.MessageTypeProto.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.kanven.schedual.network.protoc.RequestProto.Ping ping_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kanven.schedual.network.protoc.RequestProto.Ping, com.kanven.schedual.network.protoc.RequestProto.Ping.Builder, com.kanven.schedual.network.protoc.RequestProto.PingOrBuilder> pingBuilder_;
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Ping ping = 3;</code>
       */
      public boolean hasPing() {
        return pingBuilder_ != null || ping_ != null;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Ping ping = 3;</code>
       */
      public com.kanven.schedual.network.protoc.RequestProto.Ping getPing() {
        if (pingBuilder_ == null) {
          return ping_ == null ? com.kanven.schedual.network.protoc.RequestProto.Ping.getDefaultInstance() : ping_;
        } else {
          return pingBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Ping ping = 3;</code>
       */
      public Builder setPing(com.kanven.schedual.network.protoc.RequestProto.Ping value) {
        if (pingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ping_ = value;
          onChanged();
        } else {
          pingBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Ping ping = 3;</code>
       */
      public Builder setPing(
          com.kanven.schedual.network.protoc.RequestProto.Ping.Builder builderForValue) {
        if (pingBuilder_ == null) {
          ping_ = builderForValue.build();
          onChanged();
        } else {
          pingBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Ping ping = 3;</code>
       */
      public Builder mergePing(com.kanven.schedual.network.protoc.RequestProto.Ping value) {
        if (pingBuilder_ == null) {
          if (ping_ != null) {
            ping_ =
              com.kanven.schedual.network.protoc.RequestProto.Ping.newBuilder(ping_).mergeFrom(value).buildPartial();
          } else {
            ping_ = value;
          }
          onChanged();
        } else {
          pingBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Ping ping = 3;</code>
       */
      public Builder clearPing() {
        if (pingBuilder_ == null) {
          ping_ = null;
          onChanged();
        } else {
          ping_ = null;
          pingBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Ping ping = 3;</code>
       */
      public com.kanven.schedual.network.protoc.RequestProto.Ping.Builder getPingBuilder() {
        
        onChanged();
        return getPingFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Ping ping = 3;</code>
       */
      public com.kanven.schedual.network.protoc.RequestProto.PingOrBuilder getPingOrBuilder() {
        if (pingBuilder_ != null) {
          return pingBuilder_.getMessageOrBuilder();
        } else {
          return ping_ == null ?
              com.kanven.schedual.network.protoc.RequestProto.Ping.getDefaultInstance() : ping_;
        }
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Ping ping = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kanven.schedual.network.protoc.RequestProto.Ping, com.kanven.schedual.network.protoc.RequestProto.Ping.Builder, com.kanven.schedual.network.protoc.RequestProto.PingOrBuilder> 
          getPingFieldBuilder() {
        if (pingBuilder_ == null) {
          pingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kanven.schedual.network.protoc.RequestProto.Ping, com.kanven.schedual.network.protoc.RequestProto.Ping.Builder, com.kanven.schedual.network.protoc.RequestProto.PingOrBuilder>(
                  getPing(),
                  getParentForChildren(),
                  isClean());
          ping_ = null;
        }
        return pingBuilder_;
      }

      private com.kanven.schedual.network.protoc.RequestProto.Task task_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kanven.schedual.network.protoc.RequestProto.Task, com.kanven.schedual.network.protoc.RequestProto.Task.Builder, com.kanven.schedual.network.protoc.RequestProto.TaskOrBuilder> taskBuilder_;
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      public boolean hasTask() {
        return taskBuilder_ != null || task_ != null;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      public com.kanven.schedual.network.protoc.RequestProto.Task getTask() {
        if (taskBuilder_ == null) {
          return task_ == null ? com.kanven.schedual.network.protoc.RequestProto.Task.getDefaultInstance() : task_;
        } else {
          return taskBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      public Builder setTask(com.kanven.schedual.network.protoc.RequestProto.Task value) {
        if (taskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          task_ = value;
          onChanged();
        } else {
          taskBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      public Builder setTask(
          com.kanven.schedual.network.protoc.RequestProto.Task.Builder builderForValue) {
        if (taskBuilder_ == null) {
          task_ = builderForValue.build();
          onChanged();
        } else {
          taskBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      public Builder mergeTask(com.kanven.schedual.network.protoc.RequestProto.Task value) {
        if (taskBuilder_ == null) {
          if (task_ != null) {
            task_ =
              com.kanven.schedual.network.protoc.RequestProto.Task.newBuilder(task_).mergeFrom(value).buildPartial();
          } else {
            task_ = value;
          }
          onChanged();
        } else {
          taskBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      public Builder clearTask() {
        if (taskBuilder_ == null) {
          task_ = null;
          onChanged();
        } else {
          task_ = null;
          taskBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      public com.kanven.schedual.network.protoc.RequestProto.Task.Builder getTaskBuilder() {
        
        onChanged();
        return getTaskFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      public com.kanven.schedual.network.protoc.RequestProto.TaskOrBuilder getTaskOrBuilder() {
        if (taskBuilder_ != null) {
          return taskBuilder_.getMessageOrBuilder();
        } else {
          return task_ == null ?
              com.kanven.schedual.network.protoc.RequestProto.Task.getDefaultInstance() : task_;
        }
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kanven.schedual.network.protoc.RequestProto.Task, com.kanven.schedual.network.protoc.RequestProto.Task.Builder, com.kanven.schedual.network.protoc.RequestProto.TaskOrBuilder> 
          getTaskFieldBuilder() {
        if (taskBuilder_ == null) {
          taskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kanven.schedual.network.protoc.RequestProto.Task, com.kanven.schedual.network.protoc.RequestProto.Task.Builder, com.kanven.schedual.network.protoc.RequestProto.TaskOrBuilder>(
                  getTask(),
                  getParentForChildren(),
                  isClean());
          task_ = null;
        }
        return taskBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.kanven.schedual.network.protoc.Request)
    }

    // @@protoc_insertion_point(class_scope:com.kanven.schedual.network.protoc.Request)
    private static final com.kanven.schedual.network.protoc.RequestProto.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kanven.schedual.network.protoc.RequestProto.Request();
    }

    public static com.kanven.schedual.network.protoc.RequestProto.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public com.kanven.schedual.network.protoc.RequestProto.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kanven.schedual.network.protoc.Ping)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 time = 1;</code>
     */
    long getTime();
  }
  /**
   * Protobuf type {@code com.kanven.schedual.network.protoc.Ping}
   */
  public  static final class Ping extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kanven.schedual.network.protoc.Ping)
      PingOrBuilder {
    // Use Ping.newBuilder() to construct.
    private Ping(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Ping() {
      time_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Ping(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              time_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Ping_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Ping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kanven.schedual.network.protoc.RequestProto.Ping.class, com.kanven.schedual.network.protoc.RequestProto.Ping.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>optional int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (time_ != 0L) {
        output.writeInt64(1, time_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kanven.schedual.network.protoc.RequestProto.Ping)) {
        return super.equals(obj);
      }
      com.kanven.schedual.network.protoc.RequestProto.Ping other = (com.kanven.schedual.network.protoc.RequestProto.Ping) obj;

      boolean result = true;
      result = result && (getTime()
          == other.getTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kanven.schedual.network.protoc.RequestProto.Ping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Ping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Ping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Ping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Ping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Ping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Ping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Ping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Ping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Ping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kanven.schedual.network.protoc.RequestProto.Ping prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kanven.schedual.network.protoc.Ping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kanven.schedual.network.protoc.Ping)
        com.kanven.schedual.network.protoc.RequestProto.PingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Ping_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Ping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kanven.schedual.network.protoc.RequestProto.Ping.class, com.kanven.schedual.network.protoc.RequestProto.Ping.Builder.class);
      }

      // Construct using com.kanven.schedual.network.protoc.RequestProto.Ping.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        time_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Ping_descriptor;
      }

      public com.kanven.schedual.network.protoc.RequestProto.Ping getDefaultInstanceForType() {
        return com.kanven.schedual.network.protoc.RequestProto.Ping.getDefaultInstance();
      }

      public com.kanven.schedual.network.protoc.RequestProto.Ping build() {
        com.kanven.schedual.network.protoc.RequestProto.Ping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kanven.schedual.network.protoc.RequestProto.Ping buildPartial() {
        com.kanven.schedual.network.protoc.RequestProto.Ping result = new com.kanven.schedual.network.protoc.RequestProto.Ping(this);
        result.time_ = time_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kanven.schedual.network.protoc.RequestProto.Ping) {
          return mergeFrom((com.kanven.schedual.network.protoc.RequestProto.Ping)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kanven.schedual.network.protoc.RequestProto.Ping other) {
        if (other == com.kanven.schedual.network.protoc.RequestProto.Ping.getDefaultInstance()) return this;
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kanven.schedual.network.protoc.RequestProto.Ping parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kanven.schedual.network.protoc.RequestProto.Ping) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long time_ ;
      /**
       * <code>optional int64 time = 1;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional int64 time = 1;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 time = 1;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.kanven.schedual.network.protoc.Ping)
    }

    // @@protoc_insertion_point(class_scope:com.kanven.schedual.network.protoc.Ping)
    private static final com.kanven.schedual.network.protoc.RequestProto.Ping DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kanven.schedual.network.protoc.RequestProto.Ping();
    }

    public static com.kanven.schedual.network.protoc.RequestProto.Ping getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Ping>
        PARSER = new com.google.protobuf.AbstractParser<Ping>() {
      public Ping parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Ping(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Ping> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ping> getParserForType() {
      return PARSER;
    }

    public com.kanven.schedual.network.protoc.RequestProto.Ping getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kanven.schedual.network.protoc.Task)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional string group = 2;</code>
     */
    java.lang.String getGroup();
    /**
     * <code>optional string group = 2;</code>
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string url = 4;</code>
     */
    java.lang.String getUrl();
    /**
     * <code>optional string url = 4;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>optional string cron = 5;</code>
     */
    java.lang.String getCron();
    /**
     * <code>optional string cron = 5;</code>
     */
    com.google.protobuf.ByteString
        getCronBytes();

    /**
     * <code>optional int64 startTime = 6;</code>
     */
    long getStartTime();
  }
  /**
   * <pre>
   *任务实体
   * </pre>
   *
   * Protobuf type {@code com.kanven.schedual.network.protoc.Task}
   */
  public  static final class Task extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kanven.schedual.network.protoc.Task)
      TaskOrBuilder {
    // Use Task.newBuilder() to construct.
    private Task(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Task() {
      id_ = 0L;
      group_ = "";
      name_ = "";
      url_ = "";
      cron_ = "";
      startTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Task(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              group_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              cron_ = s;
              break;
            }
            case 48: {

              startTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Task_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Task_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kanven.schedual.network.protoc.RequestProto.Task.class, com.kanven.schedual.network.protoc.RequestProto.Task.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int GROUP_FIELD_NUMBER = 2;
    private volatile java.lang.Object group_;
    /**
     * <code>optional string group = 2;</code>
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      }
    }
    /**
     * <code>optional string group = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URL_FIELD_NUMBER = 4;
    private volatile java.lang.Object url_;
    /**
     * <code>optional string url = 4;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>optional string url = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CRON_FIELD_NUMBER = 5;
    private volatile java.lang.Object cron_;
    /**
     * <code>optional string cron = 5;</code>
     */
    public java.lang.String getCron() {
      java.lang.Object ref = cron_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cron_ = s;
        return s;
      }
    }
    /**
     * <code>optional string cron = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCronBytes() {
      java.lang.Object ref = cron_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cron_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTTIME_FIELD_NUMBER = 6;
    private long startTime_;
    /**
     * <code>optional int64 startTime = 6;</code>
     */
    public long getStartTime() {
      return startTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getGroupBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, group_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, url_);
      }
      if (!getCronBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cron_);
      }
      if (startTime_ != 0L) {
        output.writeInt64(6, startTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getGroupBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, group_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, url_);
      }
      if (!getCronBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, cron_);
      }
      if (startTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, startTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kanven.schedual.network.protoc.RequestProto.Task)) {
        return super.equals(obj);
      }
      com.kanven.schedual.network.protoc.RequestProto.Task other = (com.kanven.schedual.network.protoc.RequestProto.Task) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getGroup()
          .equals(other.getGroup());
      result = result && getName()
          .equals(other.getName());
      result = result && getUrl()
          .equals(other.getUrl());
      result = result && getCron()
          .equals(other.getCron());
      result = result && (getStartTime()
          == other.getStartTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + CRON_FIELD_NUMBER;
      hash = (53 * hash) + getCron().hashCode();
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kanven.schedual.network.protoc.RequestProto.Task parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kanven.schedual.network.protoc.RequestProto.Task prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *任务实体
     * </pre>
     *
     * Protobuf type {@code com.kanven.schedual.network.protoc.Task}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kanven.schedual.network.protoc.Task)
        com.kanven.schedual.network.protoc.RequestProto.TaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Task_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Task_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kanven.schedual.network.protoc.RequestProto.Task.class, com.kanven.schedual.network.protoc.RequestProto.Task.Builder.class);
      }

      // Construct using com.kanven.schedual.network.protoc.RequestProto.Task.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        group_ = "";

        name_ = "";

        url_ = "";

        cron_ = "";

        startTime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Task_descriptor;
      }

      public com.kanven.schedual.network.protoc.RequestProto.Task getDefaultInstanceForType() {
        return com.kanven.schedual.network.protoc.RequestProto.Task.getDefaultInstance();
      }

      public com.kanven.schedual.network.protoc.RequestProto.Task build() {
        com.kanven.schedual.network.protoc.RequestProto.Task result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kanven.schedual.network.protoc.RequestProto.Task buildPartial() {
        com.kanven.schedual.network.protoc.RequestProto.Task result = new com.kanven.schedual.network.protoc.RequestProto.Task(this);
        result.id_ = id_;
        result.group_ = group_;
        result.name_ = name_;
        result.url_ = url_;
        result.cron_ = cron_;
        result.startTime_ = startTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kanven.schedual.network.protoc.RequestProto.Task) {
          return mergeFrom((com.kanven.schedual.network.protoc.RequestProto.Task)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kanven.schedual.network.protoc.RequestProto.Task other) {
        if (other == com.kanven.schedual.network.protoc.RequestProto.Task.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getGroup().isEmpty()) {
          group_ = other.group_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (!other.getCron().isEmpty()) {
          cron_ = other.cron_;
          onChanged();
        }
        if (other.getStartTime() != 0L) {
          setStartTime(other.getStartTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kanven.schedual.network.protoc.RequestProto.Task parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kanven.schedual.network.protoc.RequestProto.Task) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object group_ = "";
      /**
       * <code>optional string group = 2;</code>
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string group = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string group = 2;</code>
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string group = 2;</code>
       */
      public Builder clearGroup() {
        
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      /**
       * <code>optional string group = 2;</code>
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        group_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <code>optional string url = 4;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string url = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string url = 4;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 4;</code>
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 4;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cron_ = "";
      /**
       * <code>optional string cron = 5;</code>
       */
      public java.lang.String getCron() {
        java.lang.Object ref = cron_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cron_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cron = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCronBytes() {
        java.lang.Object ref = cron_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cron_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cron = 5;</code>
       */
      public Builder setCron(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cron_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cron = 5;</code>
       */
      public Builder clearCron() {
        
        cron_ = getDefaultInstance().getCron();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cron = 5;</code>
       */
      public Builder setCronBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cron_ = value;
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <code>optional int64 startTime = 6;</code>
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>optional int64 startTime = 6;</code>
       */
      public Builder setStartTime(long value) {
        
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 startTime = 6;</code>
       */
      public Builder clearStartTime() {
        
        startTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.kanven.schedual.network.protoc.Task)
    }

    // @@protoc_insertion_point(class_scope:com.kanven.schedual.network.protoc.Task)
    private static final com.kanven.schedual.network.protoc.RequestProto.Task DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kanven.schedual.network.protoc.RequestProto.Task();
    }

    public static com.kanven.schedual.network.protoc.RequestProto.Task getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Task>
        PARSER = new com.google.protobuf.AbstractParser<Task>() {
      public Task parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Task(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Task> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Task> getParserForType() {
      return PARSER;
    }

    public com.kanven.schedual.network.protoc.RequestProto.Task getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kanven_schedual_network_protoc_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kanven_schedual_network_protoc_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kanven_schedual_network_protoc_Ping_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kanven_schedual_network_protoc_Ping_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kanven_schedual_network_protoc_Task_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kanven_schedual_network_protoc_Task_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRequest.proto\022\"com.kanven.schedual.net" +
      "work.protoc\032\021MessageType.proto\"\313\001\n\007Reque" +
      "st\022\021\n\trequestId\030\001 \001(\t\022=\n\004type\030\002 \001(\0162/.co" +
      "m.kanven.schedual.network.protoc.Message" +
      "Type\0226\n\004ping\030\003 \001(\0132(.com.kanven.schedual" +
      ".network.protoc.Ping\0226\n\004task\030\004 \001(\0132(.com" +
      ".kanven.schedual.network.protoc.Task\"\024\n\004" +
      "Ping\022\014\n\004time\030\001 \001(\003\"]\n\004Task\022\n\n\002id\030\001 \001(\003\022\r" +
      "\n\005group\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\013\n\003url\030\004 \001(\t" +
      "\022\014\n\004cron\030\005 \001(\t\022\021\n\tstartTime\030\006 \001(\003B\016B\014Req",
      "uestProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kanven.schedual.network.protoc.MessageTypeProto.getDescriptor(),
        }, assigner);
    internal_static_com_kanven_schedual_network_protoc_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kanven_schedual_network_protoc_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kanven_schedual_network_protoc_Request_descriptor,
        new java.lang.String[] { "RequestId", "Type", "Ping", "Task", });
    internal_static_com_kanven_schedual_network_protoc_Ping_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_kanven_schedual_network_protoc_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kanven_schedual_network_protoc_Ping_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_com_kanven_schedual_network_protoc_Task_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_kanven_schedual_network_protoc_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kanven_schedual_network_protoc_Task_descriptor,
        new java.lang.String[] { "Id", "Group", "Name", "Url", "Cron", "StartTime", });
    com.kanven.schedual.network.protoc.MessageTypeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
