// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package com.kanven.schedual.network.protoc;

public final class RequestProto {
  private RequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *任务类型
   * </pre>
   *
   * Protobuf enum {@code com.kanven.schedual.network.protoc.TaskKind}
   */
  public enum TaskKind
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *定时任务
     * </pre>
     *
     * <code>TIME = 0;</code>
     */
    TIME(0),
    /**
     * <pre>
     *延时任务
     * </pre>
     *
     * <code>DELAY = 1;</code>
     */
    DELAY(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *定时任务
     * </pre>
     *
     * <code>TIME = 0;</code>
     */
    public static final int TIME_VALUE = 0;
    /**
     * <pre>
     *延时任务
     * </pre>
     *
     * <code>DELAY = 1;</code>
     */
    public static final int DELAY_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TaskKind valueOf(int value) {
      return forNumber(value);
    }

    public static TaskKind forNumber(int value) {
      switch (value) {
        case 0: return TIME;
        case 1: return DELAY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TaskKind>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TaskKind> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TaskKind>() {
            public TaskKind findValueByNumber(int number) {
              return TaskKind.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kanven.schedual.network.protoc.RequestProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final TaskKind[] VALUES = values();

    public static TaskKind valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TaskKind(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.kanven.schedual.network.protoc.TaskKind)
  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kanven.schedual.network.protoc.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string requestId = 1;</code>
     */
    java.lang.String getRequestId();
    /**
     * <code>optional string requestId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
     */
    com.kanven.schedual.network.protoc.MessageTypeProto.MessageType getType();

    /**
     * <code>optional .com.kanven.schedual.network.protoc.Server server = 3;</code>
     */
    boolean hasServer();
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Server server = 3;</code>
     */
    com.kanven.schedual.network.protoc.RequestProto.Server getServer();
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Server server = 3;</code>
     */
    com.kanven.schedual.network.protoc.RequestProto.ServerOrBuilder getServerOrBuilder();

    /**
     * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
     */
    boolean hasTask();
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
     */
    com.kanven.schedual.network.protoc.RequestProto.Task getTask();
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
     */
    com.kanven.schedual.network.protoc.RequestProto.TaskOrBuilder getTaskOrBuilder();
  }
  /**
   * <pre>
   *请求实体
   * </pre>
   *
   * Protobuf type {@code com.kanven.schedual.network.protoc.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kanven.schedual.network.protoc.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      requestId_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              com.kanven.schedual.network.protoc.RequestProto.Server.Builder subBuilder = null;
              if (server_ != null) {
                subBuilder = server_.toBuilder();
              }
              server_ = input.readMessage(com.kanven.schedual.network.protoc.RequestProto.Server.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(server_);
                server_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.kanven.schedual.network.protoc.RequestProto.Task.Builder subBuilder = null;
              if (task_ != null) {
                subBuilder = task_.toBuilder();
              }
              task_ = input.readMessage(com.kanven.schedual.network.protoc.RequestProto.Task.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(task_);
                task_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kanven.schedual.network.protoc.RequestProto.Request.class, com.kanven.schedual.network.protoc.RequestProto.Request.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestId_;
    /**
     * <code>optional string requestId = 1;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string requestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
     */
    public com.kanven.schedual.network.protoc.MessageTypeProto.MessageType getType() {
      com.kanven.schedual.network.protoc.MessageTypeProto.MessageType result = com.kanven.schedual.network.protoc.MessageTypeProto.MessageType.valueOf(type_);
      return result == null ? com.kanven.schedual.network.protoc.MessageTypeProto.MessageType.UNRECOGNIZED : result;
    }

    public static final int SERVER_FIELD_NUMBER = 3;
    private com.kanven.schedual.network.protoc.RequestProto.Server server_;
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Server server = 3;</code>
     */
    public boolean hasServer() {
      return server_ != null;
    }
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Server server = 3;</code>
     */
    public com.kanven.schedual.network.protoc.RequestProto.Server getServer() {
      return server_ == null ? com.kanven.schedual.network.protoc.RequestProto.Server.getDefaultInstance() : server_;
    }
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Server server = 3;</code>
     */
    public com.kanven.schedual.network.protoc.RequestProto.ServerOrBuilder getServerOrBuilder() {
      return getServer();
    }

    public static final int TASK_FIELD_NUMBER = 4;
    private com.kanven.schedual.network.protoc.RequestProto.Task task_;
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
     */
    public boolean hasTask() {
      return task_ != null;
    }
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
     */
    public com.kanven.schedual.network.protoc.RequestProto.Task getTask() {
      return task_ == null ? com.kanven.schedual.network.protoc.RequestProto.Task.getDefaultInstance() : task_;
    }
    /**
     * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
     */
    public com.kanven.schedual.network.protoc.RequestProto.TaskOrBuilder getTaskOrBuilder() {
      return getTask();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
      }
      if (type_ != com.kanven.schedual.network.protoc.MessageTypeProto.MessageType.SERVER.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (server_ != null) {
        output.writeMessage(3, getServer());
      }
      if (task_ != null) {
        output.writeMessage(4, getTask());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
      }
      if (type_ != com.kanven.schedual.network.protoc.MessageTypeProto.MessageType.SERVER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (server_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getServer());
      }
      if (task_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getTask());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kanven.schedual.network.protoc.RequestProto.Request)) {
        return super.equals(obj);
      }
      com.kanven.schedual.network.protoc.RequestProto.Request other = (com.kanven.schedual.network.protoc.RequestProto.Request) obj;

      boolean result = true;
      result = result && getRequestId()
          .equals(other.getRequestId());
      result = result && type_ == other.type_;
      result = result && (hasServer() == other.hasServer());
      if (hasServer()) {
        result = result && getServer()
            .equals(other.getServer());
      }
      result = result && (hasTask() == other.hasTask());
      if (hasTask()) {
        result = result && getTask()
            .equals(other.getTask());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasServer()) {
        hash = (37 * hash) + SERVER_FIELD_NUMBER;
        hash = (53 * hash) + getServer().hashCode();
      }
      if (hasTask()) {
        hash = (37 * hash) + TASK_FIELD_NUMBER;
        hash = (53 * hash) + getTask().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kanven.schedual.network.protoc.RequestProto.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kanven.schedual.network.protoc.RequestProto.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求实体
     * </pre>
     *
     * Protobuf type {@code com.kanven.schedual.network.protoc.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kanven.schedual.network.protoc.Request)
        com.kanven.schedual.network.protoc.RequestProto.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kanven.schedual.network.protoc.RequestProto.Request.class, com.kanven.schedual.network.protoc.RequestProto.Request.Builder.class);
      }

      // Construct using com.kanven.schedual.network.protoc.RequestProto.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestId_ = "";

        type_ = 0;

        if (serverBuilder_ == null) {
          server_ = null;
        } else {
          server_ = null;
          serverBuilder_ = null;
        }
        if (taskBuilder_ == null) {
          task_ = null;
        } else {
          task_ = null;
          taskBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Request_descriptor;
      }

      public com.kanven.schedual.network.protoc.RequestProto.Request getDefaultInstanceForType() {
        return com.kanven.schedual.network.protoc.RequestProto.Request.getDefaultInstance();
      }

      public com.kanven.schedual.network.protoc.RequestProto.Request build() {
        com.kanven.schedual.network.protoc.RequestProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kanven.schedual.network.protoc.RequestProto.Request buildPartial() {
        com.kanven.schedual.network.protoc.RequestProto.Request result = new com.kanven.schedual.network.protoc.RequestProto.Request(this);
        result.requestId_ = requestId_;
        result.type_ = type_;
        if (serverBuilder_ == null) {
          result.server_ = server_;
        } else {
          result.server_ = serverBuilder_.build();
        }
        if (taskBuilder_ == null) {
          result.task_ = task_;
        } else {
          result.task_ = taskBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kanven.schedual.network.protoc.RequestProto.Request) {
          return mergeFrom((com.kanven.schedual.network.protoc.RequestProto.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kanven.schedual.network.protoc.RequestProto.Request other) {
        if (other == com.kanven.schedual.network.protoc.RequestProto.Request.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasServer()) {
          mergeServer(other.getServer());
        }
        if (other.hasTask()) {
          mergeTask(other.getTask());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kanven.schedual.network.protoc.RequestProto.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kanven.schedual.network.protoc.RequestProto.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requestId_ = "";
      /**
       * <code>optional string requestId = 1;</code>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestId = 1;</code>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestId = 1;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestId_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
       */
      public com.kanven.schedual.network.protoc.MessageTypeProto.MessageType getType() {
        com.kanven.schedual.network.protoc.MessageTypeProto.MessageType result = com.kanven.schedual.network.protoc.MessageTypeProto.MessageType.valueOf(type_);
        return result == null ? com.kanven.schedual.network.protoc.MessageTypeProto.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
       */
      public Builder setType(com.kanven.schedual.network.protoc.MessageTypeProto.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.MessageType type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.kanven.schedual.network.protoc.RequestProto.Server server_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kanven.schedual.network.protoc.RequestProto.Server, com.kanven.schedual.network.protoc.RequestProto.Server.Builder, com.kanven.schedual.network.protoc.RequestProto.ServerOrBuilder> serverBuilder_;
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Server server = 3;</code>
       */
      public boolean hasServer() {
        return serverBuilder_ != null || server_ != null;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Server server = 3;</code>
       */
      public com.kanven.schedual.network.protoc.RequestProto.Server getServer() {
        if (serverBuilder_ == null) {
          return server_ == null ? com.kanven.schedual.network.protoc.RequestProto.Server.getDefaultInstance() : server_;
        } else {
          return serverBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Server server = 3;</code>
       */
      public Builder setServer(com.kanven.schedual.network.protoc.RequestProto.Server value) {
        if (serverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          server_ = value;
          onChanged();
        } else {
          serverBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Server server = 3;</code>
       */
      public Builder setServer(
          com.kanven.schedual.network.protoc.RequestProto.Server.Builder builderForValue) {
        if (serverBuilder_ == null) {
          server_ = builderForValue.build();
          onChanged();
        } else {
          serverBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Server server = 3;</code>
       */
      public Builder mergeServer(com.kanven.schedual.network.protoc.RequestProto.Server value) {
        if (serverBuilder_ == null) {
          if (server_ != null) {
            server_ =
              com.kanven.schedual.network.protoc.RequestProto.Server.newBuilder(server_).mergeFrom(value).buildPartial();
          } else {
            server_ = value;
          }
          onChanged();
        } else {
          serverBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Server server = 3;</code>
       */
      public Builder clearServer() {
        if (serverBuilder_ == null) {
          server_ = null;
          onChanged();
        } else {
          server_ = null;
          serverBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Server server = 3;</code>
       */
      public com.kanven.schedual.network.protoc.RequestProto.Server.Builder getServerBuilder() {
        
        onChanged();
        return getServerFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Server server = 3;</code>
       */
      public com.kanven.schedual.network.protoc.RequestProto.ServerOrBuilder getServerOrBuilder() {
        if (serverBuilder_ != null) {
          return serverBuilder_.getMessageOrBuilder();
        } else {
          return server_ == null ?
              com.kanven.schedual.network.protoc.RequestProto.Server.getDefaultInstance() : server_;
        }
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Server server = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kanven.schedual.network.protoc.RequestProto.Server, com.kanven.schedual.network.protoc.RequestProto.Server.Builder, com.kanven.schedual.network.protoc.RequestProto.ServerOrBuilder> 
          getServerFieldBuilder() {
        if (serverBuilder_ == null) {
          serverBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kanven.schedual.network.protoc.RequestProto.Server, com.kanven.schedual.network.protoc.RequestProto.Server.Builder, com.kanven.schedual.network.protoc.RequestProto.ServerOrBuilder>(
                  getServer(),
                  getParentForChildren(),
                  isClean());
          server_ = null;
        }
        return serverBuilder_;
      }

      private com.kanven.schedual.network.protoc.RequestProto.Task task_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kanven.schedual.network.protoc.RequestProto.Task, com.kanven.schedual.network.protoc.RequestProto.Task.Builder, com.kanven.schedual.network.protoc.RequestProto.TaskOrBuilder> taskBuilder_;
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      public boolean hasTask() {
        return taskBuilder_ != null || task_ != null;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      public com.kanven.schedual.network.protoc.RequestProto.Task getTask() {
        if (taskBuilder_ == null) {
          return task_ == null ? com.kanven.schedual.network.protoc.RequestProto.Task.getDefaultInstance() : task_;
        } else {
          return taskBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      public Builder setTask(com.kanven.schedual.network.protoc.RequestProto.Task value) {
        if (taskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          task_ = value;
          onChanged();
        } else {
          taskBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      public Builder setTask(
          com.kanven.schedual.network.protoc.RequestProto.Task.Builder builderForValue) {
        if (taskBuilder_ == null) {
          task_ = builderForValue.build();
          onChanged();
        } else {
          taskBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      public Builder mergeTask(com.kanven.schedual.network.protoc.RequestProto.Task value) {
        if (taskBuilder_ == null) {
          if (task_ != null) {
            task_ =
              com.kanven.schedual.network.protoc.RequestProto.Task.newBuilder(task_).mergeFrom(value).buildPartial();
          } else {
            task_ = value;
          }
          onChanged();
        } else {
          taskBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      public Builder clearTask() {
        if (taskBuilder_ == null) {
          task_ = null;
          onChanged();
        } else {
          task_ = null;
          taskBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      public com.kanven.schedual.network.protoc.RequestProto.Task.Builder getTaskBuilder() {
        
        onChanged();
        return getTaskFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      public com.kanven.schedual.network.protoc.RequestProto.TaskOrBuilder getTaskOrBuilder() {
        if (taskBuilder_ != null) {
          return taskBuilder_.getMessageOrBuilder();
        } else {
          return task_ == null ?
              com.kanven.schedual.network.protoc.RequestProto.Task.getDefaultInstance() : task_;
        }
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.Task task = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kanven.schedual.network.protoc.RequestProto.Task, com.kanven.schedual.network.protoc.RequestProto.Task.Builder, com.kanven.schedual.network.protoc.RequestProto.TaskOrBuilder> 
          getTaskFieldBuilder() {
        if (taskBuilder_ == null) {
          taskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kanven.schedual.network.protoc.RequestProto.Task, com.kanven.schedual.network.protoc.RequestProto.Task.Builder, com.kanven.schedual.network.protoc.RequestProto.TaskOrBuilder>(
                  getTask(),
                  getParentForChildren(),
                  isClean());
          task_ = null;
        }
        return taskBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.kanven.schedual.network.protoc.Request)
    }

    // @@protoc_insertion_point(class_scope:com.kanven.schedual.network.protoc.Request)
    private static final com.kanven.schedual.network.protoc.RequestProto.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kanven.schedual.network.protoc.RequestProto.Request();
    }

    public static com.kanven.schedual.network.protoc.RequestProto.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public com.kanven.schedual.network.protoc.RequestProto.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kanven.schedual.network.protoc.Server)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string ip = 1;</code>
     */
    java.lang.String getIp();
    /**
     * <code>optional string ip = 1;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>optional int32 port = 2;</code>
     */
    int getPort();

    /**
     * <code>optional bool master = 3;</code>
     */
    boolean getMaster();
  }
  /**
   * <pre>
   *服务信息实体
   * </pre>
   *
   * Protobuf type {@code com.kanven.schedual.network.protoc.Server}
   */
  public  static final class Server extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kanven.schedual.network.protoc.Server)
      ServerOrBuilder {
    // Use Server.newBuilder() to construct.
    private Server(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Server() {
      ip_ = "";
      port_ = 0;
      master_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Server(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 16: {

              port_ = input.readInt32();
              break;
            }
            case 24: {

              master_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Server_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Server_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kanven.schedual.network.protoc.RequestProto.Server.class, com.kanven.schedual.network.protoc.RequestProto.Server.Builder.class);
    }

    public static final int IP_FIELD_NUMBER = 1;
    private volatile java.lang.Object ip_;
    /**
     * <code>optional string ip = 1;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ip = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>optional int32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int MASTER_FIELD_NUMBER = 3;
    private boolean master_;
    /**
     * <code>optional bool master = 3;</code>
     */
    public boolean getMaster() {
      return master_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ip_);
      }
      if (port_ != 0) {
        output.writeInt32(2, port_);
      }
      if (master_ != false) {
        output.writeBool(3, master_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ip_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      if (master_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, master_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kanven.schedual.network.protoc.RequestProto.Server)) {
        return super.equals(obj);
      }
      com.kanven.schedual.network.protoc.RequestProto.Server other = (com.kanven.schedual.network.protoc.RequestProto.Server) obj;

      boolean result = true;
      result = result && getIp()
          .equals(other.getIp());
      result = result && (getPort()
          == other.getPort());
      result = result && (getMaster()
          == other.getMaster());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + MASTER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMaster());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kanven.schedual.network.protoc.RequestProto.Server parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Server parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Server parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Server parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Server parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Server parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Server parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Server parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Server parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Server parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kanven.schedual.network.protoc.RequestProto.Server prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *服务信息实体
     * </pre>
     *
     * Protobuf type {@code com.kanven.schedual.network.protoc.Server}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kanven.schedual.network.protoc.Server)
        com.kanven.schedual.network.protoc.RequestProto.ServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Server_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Server_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kanven.schedual.network.protoc.RequestProto.Server.class, com.kanven.schedual.network.protoc.RequestProto.Server.Builder.class);
      }

      // Construct using com.kanven.schedual.network.protoc.RequestProto.Server.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ip_ = "";

        port_ = 0;

        master_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Server_descriptor;
      }

      public com.kanven.schedual.network.protoc.RequestProto.Server getDefaultInstanceForType() {
        return com.kanven.schedual.network.protoc.RequestProto.Server.getDefaultInstance();
      }

      public com.kanven.schedual.network.protoc.RequestProto.Server build() {
        com.kanven.schedual.network.protoc.RequestProto.Server result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kanven.schedual.network.protoc.RequestProto.Server buildPartial() {
        com.kanven.schedual.network.protoc.RequestProto.Server result = new com.kanven.schedual.network.protoc.RequestProto.Server(this);
        result.ip_ = ip_;
        result.port_ = port_;
        result.master_ = master_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kanven.schedual.network.protoc.RequestProto.Server) {
          return mergeFrom((com.kanven.schedual.network.protoc.RequestProto.Server)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kanven.schedual.network.protoc.RequestProto.Server other) {
        if (other == com.kanven.schedual.network.protoc.RequestProto.Server.getDefaultInstance()) return this;
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.getMaster() != false) {
          setMaster(other.getMaster());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kanven.schedual.network.protoc.RequestProto.Server parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kanven.schedual.network.protoc.RequestProto.Server) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>optional string ip = 1;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>optional int32 port = 2;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>optional int32 port = 2;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 port = 2;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private boolean master_ ;
      /**
       * <code>optional bool master = 3;</code>
       */
      public boolean getMaster() {
        return master_;
      }
      /**
       * <code>optional bool master = 3;</code>
       */
      public Builder setMaster(boolean value) {
        
        master_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool master = 3;</code>
       */
      public Builder clearMaster() {
        
        master_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.kanven.schedual.network.protoc.Server)
    }

    // @@protoc_insertion_point(class_scope:com.kanven.schedual.network.protoc.Server)
    private static final com.kanven.schedual.network.protoc.RequestProto.Server DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kanven.schedual.network.protoc.RequestProto.Server();
    }

    public static com.kanven.schedual.network.protoc.RequestProto.Server getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Server>
        PARSER = new com.google.protobuf.AbstractParser<Server>() {
      public Server parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Server(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Server> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Server> getParserForType() {
      return PARSER;
    }

    public com.kanven.schedual.network.protoc.RequestProto.Server getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kanven.schedual.network.protoc.Task)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string url = 1;</code>
     */
    java.lang.String getUrl();
    /**
     * <code>optional string url = 1;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>optional .com.kanven.schedual.network.protoc.TaskKind kind = 2;</code>
     */
    int getKindValue();
    /**
     * <code>optional .com.kanven.schedual.network.protoc.TaskKind kind = 2;</code>
     */
    com.kanven.schedual.network.protoc.RequestProto.TaskKind getKind();

    /**
     * <code>optional string cron = 3;</code>
     */
    java.lang.String getCron();
    /**
     * <code>optional string cron = 3;</code>
     */
    com.google.protobuf.ByteString
        getCronBytes();

    /**
     * <code>optional int32 delay = 4;</code>
     */
    int getDelay();
  }
  /**
   * <pre>
   *任务实体
   * </pre>
   *
   * Protobuf type {@code com.kanven.schedual.network.protoc.Task}
   */
  public  static final class Task extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kanven.schedual.network.protoc.Task)
      TaskOrBuilder {
    // Use Task.newBuilder() to construct.
    private Task(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Task() {
      url_ = "";
      kind_ = 0;
      cron_ = "";
      delay_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Task(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              kind_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              cron_ = s;
              break;
            }
            case 32: {

              delay_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Task_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Task_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kanven.schedual.network.protoc.RequestProto.Task.class, com.kanven.schedual.network.protoc.RequestProto.Task.Builder.class);
    }

    public static final int URL_FIELD_NUMBER = 1;
    private volatile java.lang.Object url_;
    /**
     * <code>optional string url = 1;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>optional string url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KIND_FIELD_NUMBER = 2;
    private int kind_;
    /**
     * <code>optional .com.kanven.schedual.network.protoc.TaskKind kind = 2;</code>
     */
    public int getKindValue() {
      return kind_;
    }
    /**
     * <code>optional .com.kanven.schedual.network.protoc.TaskKind kind = 2;</code>
     */
    public com.kanven.schedual.network.protoc.RequestProto.TaskKind getKind() {
      com.kanven.schedual.network.protoc.RequestProto.TaskKind result = com.kanven.schedual.network.protoc.RequestProto.TaskKind.valueOf(kind_);
      return result == null ? com.kanven.schedual.network.protoc.RequestProto.TaskKind.UNRECOGNIZED : result;
    }

    public static final int CRON_FIELD_NUMBER = 3;
    private volatile java.lang.Object cron_;
    /**
     * <code>optional string cron = 3;</code>
     */
    public java.lang.String getCron() {
      java.lang.Object ref = cron_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cron_ = s;
        return s;
      }
    }
    /**
     * <code>optional string cron = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCronBytes() {
      java.lang.Object ref = cron_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cron_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DELAY_FIELD_NUMBER = 4;
    private int delay_;
    /**
     * <code>optional int32 delay = 4;</code>
     */
    public int getDelay() {
      return delay_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, url_);
      }
      if (kind_ != com.kanven.schedual.network.protoc.RequestProto.TaskKind.TIME.getNumber()) {
        output.writeEnum(2, kind_);
      }
      if (!getCronBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cron_);
      }
      if (delay_ != 0) {
        output.writeInt32(4, delay_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, url_);
      }
      if (kind_ != com.kanven.schedual.network.protoc.RequestProto.TaskKind.TIME.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, kind_);
      }
      if (!getCronBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cron_);
      }
      if (delay_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, delay_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kanven.schedual.network.protoc.RequestProto.Task)) {
        return super.equals(obj);
      }
      com.kanven.schedual.network.protoc.RequestProto.Task other = (com.kanven.schedual.network.protoc.RequestProto.Task) obj;

      boolean result = true;
      result = result && getUrl()
          .equals(other.getUrl());
      result = result && kind_ == other.kind_;
      result = result && getCron()
          .equals(other.getCron());
      result = result && (getDelay()
          == other.getDelay());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + KIND_FIELD_NUMBER;
      hash = (53 * hash) + kind_;
      hash = (37 * hash) + CRON_FIELD_NUMBER;
      hash = (53 * hash) + getCron().hashCode();
      hash = (37 * hash) + DELAY_FIELD_NUMBER;
      hash = (53 * hash) + getDelay();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kanven.schedual.network.protoc.RequestProto.Task parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kanven.schedual.network.protoc.RequestProto.Task parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kanven.schedual.network.protoc.RequestProto.Task prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *任务实体
     * </pre>
     *
     * Protobuf type {@code com.kanven.schedual.network.protoc.Task}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kanven.schedual.network.protoc.Task)
        com.kanven.schedual.network.protoc.RequestProto.TaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Task_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Task_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kanven.schedual.network.protoc.RequestProto.Task.class, com.kanven.schedual.network.protoc.RequestProto.Task.Builder.class);
      }

      // Construct using com.kanven.schedual.network.protoc.RequestProto.Task.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        url_ = "";

        kind_ = 0;

        cron_ = "";

        delay_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kanven.schedual.network.protoc.RequestProto.internal_static_com_kanven_schedual_network_protoc_Task_descriptor;
      }

      public com.kanven.schedual.network.protoc.RequestProto.Task getDefaultInstanceForType() {
        return com.kanven.schedual.network.protoc.RequestProto.Task.getDefaultInstance();
      }

      public com.kanven.schedual.network.protoc.RequestProto.Task build() {
        com.kanven.schedual.network.protoc.RequestProto.Task result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kanven.schedual.network.protoc.RequestProto.Task buildPartial() {
        com.kanven.schedual.network.protoc.RequestProto.Task result = new com.kanven.schedual.network.protoc.RequestProto.Task(this);
        result.url_ = url_;
        result.kind_ = kind_;
        result.cron_ = cron_;
        result.delay_ = delay_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kanven.schedual.network.protoc.RequestProto.Task) {
          return mergeFrom((com.kanven.schedual.network.protoc.RequestProto.Task)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kanven.schedual.network.protoc.RequestProto.Task other) {
        if (other == com.kanven.schedual.network.protoc.RequestProto.Task.getDefaultInstance()) return this;
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (other.kind_ != 0) {
          setKindValue(other.getKindValue());
        }
        if (!other.getCron().isEmpty()) {
          cron_ = other.cron_;
          onChanged();
        }
        if (other.getDelay() != 0) {
          setDelay(other.getDelay());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kanven.schedual.network.protoc.RequestProto.Task parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kanven.schedual.network.protoc.RequestProto.Task) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <code>optional string url = 1;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private int kind_ = 0;
      /**
       * <code>optional .com.kanven.schedual.network.protoc.TaskKind kind = 2;</code>
       */
      public int getKindValue() {
        return kind_;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.TaskKind kind = 2;</code>
       */
      public Builder setKindValue(int value) {
        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.TaskKind kind = 2;</code>
       */
      public com.kanven.schedual.network.protoc.RequestProto.TaskKind getKind() {
        com.kanven.schedual.network.protoc.RequestProto.TaskKind result = com.kanven.schedual.network.protoc.RequestProto.TaskKind.valueOf(kind_);
        return result == null ? com.kanven.schedual.network.protoc.RequestProto.TaskKind.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.TaskKind kind = 2;</code>
       */
      public Builder setKind(com.kanven.schedual.network.protoc.RequestProto.TaskKind value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        kind_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.kanven.schedual.network.protoc.TaskKind kind = 2;</code>
       */
      public Builder clearKind() {
        
        kind_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object cron_ = "";
      /**
       * <code>optional string cron = 3;</code>
       */
      public java.lang.String getCron() {
        java.lang.Object ref = cron_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cron_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cron = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCronBytes() {
        java.lang.Object ref = cron_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cron_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cron = 3;</code>
       */
      public Builder setCron(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cron_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cron = 3;</code>
       */
      public Builder clearCron() {
        
        cron_ = getDefaultInstance().getCron();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cron = 3;</code>
       */
      public Builder setCronBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cron_ = value;
        onChanged();
        return this;
      }

      private int delay_ ;
      /**
       * <code>optional int32 delay = 4;</code>
       */
      public int getDelay() {
        return delay_;
      }
      /**
       * <code>optional int32 delay = 4;</code>
       */
      public Builder setDelay(int value) {
        
        delay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 delay = 4;</code>
       */
      public Builder clearDelay() {
        
        delay_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.kanven.schedual.network.protoc.Task)
    }

    // @@protoc_insertion_point(class_scope:com.kanven.schedual.network.protoc.Task)
    private static final com.kanven.schedual.network.protoc.RequestProto.Task DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kanven.schedual.network.protoc.RequestProto.Task();
    }

    public static com.kanven.schedual.network.protoc.RequestProto.Task getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Task>
        PARSER = new com.google.protobuf.AbstractParser<Task>() {
      public Task parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Task(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Task> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Task> getParserForType() {
      return PARSER;
    }

    public com.kanven.schedual.network.protoc.RequestProto.Task getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kanven_schedual_network_protoc_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kanven_schedual_network_protoc_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kanven_schedual_network_protoc_Server_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kanven_schedual_network_protoc_Server_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kanven_schedual_network_protoc_Task_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kanven_schedual_network_protoc_Task_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRequest.proto\022\"com.kanven.schedual.net" +
      "work.protoc\032\021MessageType.proto\"\317\001\n\007Reque" +
      "st\022\021\n\trequestId\030\001 \001(\t\022=\n\004type\030\002 \001(\0162/.co" +
      "m.kanven.schedual.network.protoc.Message" +
      "Type\022:\n\006server\030\003 \001(\0132*.com.kanven.schedu" +
      "al.network.protoc.Server\0226\n\004task\030\004 \001(\0132(" +
      ".com.kanven.schedual.network.protoc.Task" +
      "\"2\n\006Server\022\n\n\002ip\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\022\016\n\006" +
      "master\030\003 \001(\010\"l\n\004Task\022\013\n\003url\030\001 \001(\t\022:\n\004kin" +
      "d\030\002 \001(\0162,.com.kanven.schedual.network.pr",
      "otoc.TaskKind\022\014\n\004cron\030\003 \001(\t\022\r\n\005delay\030\004 \001" +
      "(\005*\037\n\010TaskKind\022\010\n\004TIME\020\000\022\t\n\005DELAY\020\001B\016B\014R" +
      "equestProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kanven.schedual.network.protoc.MessageTypeProto.getDescriptor(),
        }, assigner);
    internal_static_com_kanven_schedual_network_protoc_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kanven_schedual_network_protoc_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kanven_schedual_network_protoc_Request_descriptor,
        new java.lang.String[] { "RequestId", "Type", "Server", "Task", });
    internal_static_com_kanven_schedual_network_protoc_Server_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_kanven_schedual_network_protoc_Server_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kanven_schedual_network_protoc_Server_descriptor,
        new java.lang.String[] { "Ip", "Port", "Master", });
    internal_static_com_kanven_schedual_network_protoc_Task_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_kanven_schedual_network_protoc_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kanven_schedual_network_protoc_Task_descriptor,
        new java.lang.String[] { "Url", "Kind", "Cron", "Delay", });
    com.kanven.schedual.network.protoc.MessageTypeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
